### ISSUE TITLE
Installation not possible - Omeka-S 4.01 

### ISSUE THREAD

**Issue by DodgerNycro** [ivyrze/omeka-s-module-transcript#4]
Hi,

when trying to install the Module (.zip or git) i get the following error - any ideas? : 

<pre><code>Error: Class "Transcript\Form\ConfigForm" not found in [...]/modules/Transcript/config/module.config.php:50

Stack trace:
#0 [...]/modules/Transcript/Module.php(25): include()
#1 [...]/modules/Generic/AbstractModule.php(556): Transcript\Module->getConfig()
#2 [...]/modules/Generic/AbstractModule.php(460): Generic\AbstractModule->manageAnySettings()
#3 [...]/modules/Generic/AbstractModule.php(115): Generic\AbstractModule->manageConfig()
#4 [...]/application/src/Module/Manager.php(226): Generic\AbstractModule->install()
#5 [...]/application/src/Controller/Admin/ModuleController.php(117): Omeka\Module\Manager->install()
#6 [...]/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): Omeka\Controller\Admin\ModuleController->installAction()
#7 [...]/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch()
#8 [...]/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners()
#9 [...]/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil()
#10 [...]/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch()
#11 [...]/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch()
#12 [...]/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners()
#13 [...]/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil()
#14 [...]/index.php(21): Laminas\Mvc\Application->run()
#15 {main} {"userId":1}
</code</pre>

**Comment by ivyrze** [comment]
Thanks so much for flagging this. This should be fixed now in 9e8fa18, so if you have the capability to build from source, give it a try and let me know if you still have problems. If not, it'll be released officially in the next few weeks

**Comment by DodgerNycro** [comment]
Works lika a charm. thank you!

**Comment by ivyrze** [comment]
This patch has been released officially in 4.0.3 in case you need it. Sorry it took so long!
