### ISSUE TITLE
Transcript Text Does Not Automatically Scroll

### ISSUE THREAD

**Issue by anthony-evans** [ivyrze/omeka-s-module-transcript#7]
Hello,

Thankyou for the latest release of the module and for all your hard work.
Everything is good with the latest release apart from a bug with the text scrolling. The transcript text box (which displays the WebVTT text) does not scroll automatically anymore. The transcript text highlights correctly. Just the text box does not automatically scroll along with the text as it moves down the transcript.

![image](https://github.com/ivyrze/omeka-s-module-transcript/assets/57145243/9fd5ec1a-0afb-4233-9eaf-7dc45b744385)

Best wishes,
Tony Evans

**Comment by ivyrze** [comment]
Sorry for the lengthy delay in getting this fixed. The latest version should have this functionality once again. Let me know if you encounter any issues with it!
